Fixed Clean dropdown border
mrdokenny/Cookie-AutoDelete pull request #793
Opened 2020-07-02 12:08 UTC by Nautman

# Problem

The button doesn't look very neat.

![Rounded corners on clean buttons dropdown](https://user-images.githubusercontent.com/28629647/86356270-789fb600-bc5b-11ea-9813-f1be73ed0d02.png)

# Fix

I fixed it so that in the popup, the clean dropdown menu button has no rounded corners.

It now looks like this:
![Not rounded corners on clean buttons dropdown](https://user-images.githubusercontent.com/28629647/86356272-79d0e300-bc5b-11ea-858f-ee2eb6ef2806.png)

Compare this to the dropdowns on Bootstraps official documentation:

![Dropdown on bootstraps documentation](https://user-images.githubusercontent.com/28629647/86356476-d6cc9900-bc5b-11ea-9b9e-3d2d4fcba8e4.png)

# Potential new fix / commit
There is one benefit with the unrounded corners, and that is that it's very obvious that the menu is a separate thing from the actual button. On GitHub, they solve this by adding a border:
![GitHub dropdown button](https://user-images.githubusercontent.com/28629647/86356611-12fff980-bc5c-11ea-9450-3ca9b57593c0.png)

If you would like, I could add such a border that would look like this:

![Border dividing dropdown menu](https://user-images.githubusercontent.com/28629647/86356735-43e02e80-bc5c-11ea-98c4-a3f9b3824d29.png)

To add this, I would simply add a color to the left border.

```
borderLeftColor: '#c69500',
```

2020-07-02 12:31 UTC, Nautman commented
In hindsight I probably should have made this a draft pull request, since I'm wondering if you think it should have a colored left border... Then it also wouldn't have to perform all the checks again.

2020-07-03 01:13 UTC, kennethtran93 commented
I think the original idea came from this: https://getbootstrap.com/docs/4.1/components/dropdowns/#split-button but wasn't implemented properly.

2020-07-03 01:14 UTC, kennethtran93 commented
I'm going to take a look at reorganizing the html to make it work, but thanks for the initial contribution.

2020-07-03 02:57 UTC, kennethtran93 requested changes
Try out the commented instructions and see if it works better.  I think on my end it seems to work fine.

You can have the credits for this once you made the adjustments.

2020-07-03 02:57 UTC, kennethtran93 commented on src/ui/popup/App.tsx
> +                  borderTopLeftRadius: 0,
Found a better way - just remove the div "dropdown" parent, and add 
``` 
borderLeftColor: 'rgb(176, 132, 0)',
``` 
to the style (removing the two radius lines you added) and maybe change '-3px' to '-2px' for somewhat uniform spacing in translate3d.

See if that works better for you.

2020-07-06 06:30 UTC, kennethtran93 commented
superseded with PR#798

2020-07-06 06:30 UTC, closed without merging